[http]
bind_address = "0.0.0.0:8080"

[mysql]
address = "127.0.0.1:3306"
username = "root"
password = "helloworld"
database = "elab"
dsn = "%s:%s@tcp(%s)/%s?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"

[redis]
address = "127.0.0.1:6379"
password = ""
database = 0

[aliyun_oss]
endpoint = "https://oss-cn-shanghai.aliyuncs.com"
access_key_id = ""
access_key_secret = ""

[oidc]
issuer = "https://auth.zeithrold.com"
client_id = ""
client_secret = ""
redirect_url = "http://127.0.0.1:8080/v1/auth/callback"
