[http]
addr = "0.0.0.0:8080"
[http.oauth]
issuer = "https://auth.zeithrold.com"

[db]
addr = "127.0.0.1:3306"
user = "root"
pwd = "helloworld"
database = "Registration"
dsn = "%s:%s@tcp(%s)/%s?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"

[mobile]
endpoint = "exp://127.0.0.1:19000/callback"

[redis]
addr = "127.0.0.1:6379"
pwd = ""
DB = 0

[oidc]
issuer = "https://auth.zeithrold.com"
client_id = ""
client_secret = ""
redirect_url = "http://127.0.0.1:8080/auth/callback"
