[http]
addr = "0.0.0.0:8080"
[http.oauth]
issuer = ""

[db]
addr = "127.0.0.1:3306"
user = ""
pwd = ""
database = ""
dsn = "%s:%s@tcp(%s)/%s?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"

[redis]
addr = "127.0.0.1:6379"
pwd = ""
DB = 0

[oss]
endpoint = "http://oss-cn-shanghai.aliyuncs.com"
access_key_id = ""
access_key_secret = ""
ossPreURL = ""


[oidc]
issuer = ""
client_id = ""
client_secret = ""
redirect_url = ""

[mobile]
endpoint = ""
